### ISSUE TITLE
TypeError: writelines() argument must be a sequence of strings

### ISSUE THREAD

**Issue by emprovements** [ankitsejwal/Lyndor#12]
Hi, first of all you did a amazing job to pull this downloader.
But on some courses I am getting this error.

```
Using username and password combination for download

Course Name	Magazine Design: Getting Started
Course id	628693
Author Name	John McWade
Topics		#Design	#Page Layout	
Softwares	#InDesign	
Duration	56m 46s
Release Date	10/31/2017
Downloaded On	02/February/2018
Course URL	https://www.lynda.com/InDesign-tutorials/Magazine-Design-Getting-Started/628693-2.html

-> info.txt file created

Creating Chapters:

00. Introduction
01. Magazine Stands  A World of Design
02. Building a Magazine
03. The Front of the Book
04. The Middle and Back of the Book
05. Making a Magazine
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    main()
  File "run.py", line 28, in main
    schedule_download(url)
  File "run.py", line 44, in schedule_download
    download_course(url)
  File "run.py", line 84, in download_course
    save.chapters(url, course_folder_path)      # Create chapters inside course folder
  File "/home/mg/Lyndor/save.py", line 140, in chapters
    chapters_and_videos_to_contentmd(url)
  File "/home/mg/Lyndor/save.py", line 163, in chapters_and_videos_to_contentmd
    content_md.writelines('\n* ' + str(video_count).zfill(2) + ' - ' + video.text.strip())
TypeError: writelines() argument must be a sequence of strings

```

Any idea what could it be?

**Comment by emprovements** [comment]
Ok, so I tracked down the issue and I found out it's encoding problem with ’ character.
I fixed it with this
content_md.writelines('\n* ' + str(video_count).zfill(2) + ' - ' + video.text.encode("ascii","replace").strip())
so if you think it's good enough fix, just use it.

**Comment by ankitsejwal** [comment]
Hi @emprovements, thanks for your appreciation.
I'll try your solution, can you tell me which python version and OS are you running Lyndor on.
Curious, as there's no problem at my side on MacOS and Python 3.6.3
Thanks for your contribution.

Cheers,
Ankit

**Comment by ankitsejwal** [comment]
@emprovements your fix is not working on my side, can you try this and report back if this fixes the issue:
'''python
content_md.writelines("\n* " + str(video_count).zfill(2) + " - " + str(video.text.strip()))          
'''

**Comment by emprovements** [comment]
@ankitsejwal I will check it when I come home. But I think it's because I use python 2.7.
