### ISSUE TITLE
Issue with Desktop folder on seperate drive

### ISSUE THREAD

**Issue by theman00011** [ankitsejwal/Lyndor#14]
I have my Desktop folder located on the E drive, and was receiving

``Traceback (most recent call last):
  File "E:\Desktop\Development\Lyndor-master/run.py", line 110, in <module>
    main()
  File "E:\Desktop\Development\Lyndor-master/run.py", line 31, in main
    schedule_download(url)
  File "E:\Desktop\Development\Lyndor-master/run.py", line 47, in schedule_download
    download_course(url)
  File "E:\Desktop\Development\Lyndor-master/run.py", line 74, in download_course
    desktop_folder_path = install.folder_path("Desktop")
  File "E:\Desktop\Development\Lyndor-master\install.py", line 46, in folder_path
    os.chdir(os.path.expanduser('~/' + folder))
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Hunter/Desktop'
``

I was able to fix this by replacing line 46 in install.py

``os.chdir(os.path.expanduser('~/' + folder))
``
with
``os.chdir(os.path.expanduser('E:\' + folder))
``

**Comment by ankitsejwal** [comment]
@thefinalwolf do you have any idea???

**Comment by thefinalwolf** [comment]
@ankitsejwal I'm not really sure, I'm not too familiar with troubleshooting efficiently in Python (still learning).
@theman00011 Could you try deleting Lyndor, re-running the install.bat file, then post _only_ the **preferences** section of your settings.json file?

**Comment by rackyman** [comment]
Probably gotta use *(explicitly for windows)* -
'''os.environ['USERPROFILE']'''
instead of
'''os.path.expanduser('~')''' (works fine for unix/linux , but creates error on windows)

**Comment by rackyman** [comment]
Probably gotta use *(explicitly for windows)* -
```os.environ['USERPROFILE']```
instead of
```os.path.expanduser('~') ```*(works fine for unix/linux , but creates error on windows)*

**Comment by thefinalwolf** [comment]
@rackyman Odd you are getting an error; it works for me on both Win7 and Win10.
`os.environ['USERPROFILE']` seems to work as well so a change should be fine.

In the meantime could you open a python interpreter `python` and supply the output of the following?

```python
import sys
import os

print(sys.version_info)
path1 = os.path.expanduser('~')
path2 = os.environ['USERPROFILE']
if path1 == path2:
   print("Path1: " + path1 + " and Path2: " + path2 + " match")
else:
   print("Path1: " + path1 + " and Path2: " + path2 + " do not match")
```

**Comment by thefinalwolf** [comment]
@ankitsejwal Maybe we should close this due to no reply; I've seen similar github repos use a tag for no replies to keep things tidy. :man_shrugging:
