### ISSUE TITLE
Lyndor fails to move files in courses with more than 99 videos

### ISSUE THREAD

**Issue by AeolusDraco** [ankitsejwal/Lyndor#17]
When downloading a course with more than 99 videos, Lyndor fails to move any files numbered less than 100. This is due to the files having a leading zero in their file numbers
An example of this is the video having number of 007, when Lyndor is expecting 07.

An example of a course displaying this behavior is 
https://www.lynda.com/Blender-tutorials/Blender-Essential-Training/87088-2.html

**Comment by ankitsejwal** [comment]
Thanks for reporting @AeolusDraco, this should be fixed now.
