### ISSUE TITLE
Please Add New Features

### ISSUE THREAD

**Issue by irneo** [ankitsejwal/Lyndor#2]
Hi , Thank You For This Program 
Please Add This Feature  OR Send This Code Just For Me

# Features
## 2.  Please Add Software Tags & Subject Tags to info.txt file like as blow Code
          tutorial["subject_tags"] = [tag.text.strip() for tag in soup.findAll('a', attrs={'data-ga-label':'topic-tag'})]
          tutorial["software_tags"] = [tag.text.strip() for tag in soup.findAll('a', attrs={'data-ga-label':'software-tag'})]
## 4.  Please Add Content.txt file ( Include All Content Of Course ) like as blow Code
          def create_content_md(tutorial):
          content = open("CONTENT.md", "w")
          content.write( "# "+ tutorial["title"] + " with " + tutorial["author"] + " on lynda.com \n")
          for chapter, lectures in tutorial["chapters"].items():
          content.write( "## " + chapter + "\n")
          for lecture in lectures:
          content.write( "### " + lecture[0] + "\n")
          content.write("\n")
          content.close()
          print("\tCONTENT.md is created.")

And Very Very Thank You .

**Comment by ankitsejwal** [comment]
Hi @irneo, thanks for showing interest in this project, I have worked on the requested features and I believe the task has been completed, please have a look and test it at your end. 
If you meet some issue, please create a new issue out here as usual.
Cheers :) 👍

**Comment by irneo** [comment]
Hi Bro, Thanks For New UPdate 

#AND Please Add This Feauture
##1. Please Add Download Exercise File .
##2. Please Write CONTENT.md Code Before Save Course Chapters [ Not at Same Time ] in Folder Withe This Code:
     
	 def gather_content(url, course_path):
         content = open('CONTENT.md', 'a') as content_md:
         content.write( "# "+ course_title + " with " + author_name + " on lynda.com \n")
         for chapter, lectures in tutorial["chapters"].items():
             content.write( "## " + chapter + "\n")
             for lecture in lectures:
                 content.write( "### " + lecture[0] + "\n")
                 content.write("\n")
         content.close()
         print("\tCONTENT.md is created.")

##3. Please Save CONTENT.md Content in This Style :
     
	 For Exam: https://www.lynda.com/Marketing-Lead-Generation-tutorials/Content-Marketing-Fundamentals-2015/369044-2.html
	 CONTENT.md Is:
	 
      # Content Marketing Foundations with Dayna Rothman on lynda.com 
      ## Introduction
      ### Welcome

      ## Defining Content Marketing
      ### Defining and understanding the importance of content marketing
      ### Understanding the benefits of content marketing
      ### Defining thought leadership vs. selling

      ## Creating a Foundation for Content Marketing
      ### Hiring your content marketing team
      ### Structuring your content organization
      ### Creating buyer personas and buyer journeys
      ### Developing your brand voice
      ### Setting your content goals
      ### Choosing content technology

      ## Creating Your Content Plan
      ### Brainstorming ideas and creating your content arcs
      ### Mapping your content to the sales funnel
      ### Choosing your content types
      ### Crafting your plan and editorial calendar

      ## Creating Your Content
      ### Writing and editing
      ### Design
      ### Curating content
      ### Working with lean content creation

      ## Promoting Your Content
      ### Gating strategy
      ### Outlining a promotion strategy and alerting your organization
      ### Merchandising content on your website
      ### Promoting on social
      ### Promoting through email
      ### Promoting on your blog
      ### Syndicating your content
      ### Leveraging influencer marketing
      ### Using PPC ads to promote your content

      ## Measuring Your Content
      ### Defining your measurement goals
      ### Tracking with early-stage metrics
      ### Tracking with mid- and late-stage metrics

      ## Conclusion
      ### Next steps


AND Thank You For Support .

**Comment by irneo** [comment]
Hi Bro, Thanks For New UPdate 

#AND Please Add This Feauture
##1. Please Add Download Exercise File .
##2. Please Write CONTENT.md Code Before Save Course Chapters [ Not at Same Time ] in Folder Withe This Code:
     
	 def gather_content(url, course_path):
         content = open('CONTENT.md', 'a') as content_md:
         content.write( "# "+ course_title + " with " + author_name + " on lynda.com \n")
         for chapter, lectures in tutorial["chapters"].items():
             content.write( "## " + chapter + "\n")
             for lecture in lectures:
                 content.write( "### " + lecture[0] + "\n")
                 content.write("\n")
         content.close()
         print("\tCONTENT.md is created.")

##3. Please Save CONTENT.md Content in This Style :
     
	 For Exam: https://www.lynda.com/Marketing-Lead-Generation-tutorials/Content-Marketing-Fundamentals-2015/369044-2.html
	 CONTENT.md Is:
	 
      # Content Marketing Foundations with Dayna Rothman on lynda.com 
      ## Introduction
      ### Welcome

      ## Defining Content Marketing
      ### Defining and understanding the importance of content marketing
      ### Understanding the benefits of content marketing
      ### Defining thought leadership vs. selling

      ## Creating a Foundation for Content Marketing
      ### Hiring your content marketing team
      ### Structuring your content organization
      ### Creating buyer personas and buyer journeys
      ### Developing your brand voice
      ### Setting your content goals
      ### Choosing content technology

      ## Creating Your Content Plan
      ### Brainstorming ideas and creating your content arcs
      ### Mapping your content to the sales funnel
      ### Choosing your content types
      ### Crafting your plan and editorial calendar

      ## Creating Your Content
      ### Writing and editing
      ### Design
      ### Curating content
      ### Working with lean content creation

      ## Promoting Your Content
      ### Gating strategy
      ### Outlining a promotion strategy and alerting your organization
      ### Merchandising content on your website
      ### Promoting on social
      ### Promoting through email
      ### Promoting on your blog
      ### Syndicating your content
      ### Leveraging influencer marketing
      ### Using PPC ads to promote your content

      ## Measuring Your Content
      ### Defining your measurement goals
      ### Tracking with early-stage metrics
      ### Tracking with mid- and late-stage metrics

      ## Conclusion
      ### Next steps


AND Thank You For Support .
