### ISSUE TITLE
Failure to find some files with leading 0's for moving

### ISSUE THREAD

**Issue by thefinalwolf** [ankitsejwal/Lyndor#26]
Occasionally, leading `0`s  are removed from `video_name` and `subtitle_name` causing a failure to find files with leading `0`s. 
https://github.com/ankitsejwal/Lyndor/blob/f11d980b2d3f073f64d9d1a2c8e5fccd76220dc2/move.py#L55-L67
See attachment.
![file move](https://user-images.githubusercontent.com/9045213/38582914-31a211b0-3cc6-11e8-8820-8272e93196d2.png)

**Comment by thefinalwolf** [comment]
So far I see it has something to do with `digit` not being set to `3` sometimes.

https://github.com/ankitsejwal/Lyndor/blob/f11d980b2d3f073f64d9d1a2c8e5fccd76220dc2/move.py#L47-L49

Maybe have our count come from the number of actual videos downloaded instead of trusting the folder contents?

**Comment by ankitsejwal** [comment]
Hi, @thefinalwolf thanks for reporting this as well, currently the program counts the downloaded videos inside the folder and then it sets the 'digit' value. As you have faced this problem a better way could be to instead count the total number of videos on the website and then set the digit value (and get rid of this if block).
I'll try to implement it once I finish implementing #15.
