### ISSUE TITLE
TypeError: writelines() argument must be a sequence of strings

### ISSUE THREAD

**Issue by thefinalwolf** [ankitsejwal/Lyndor#27]
I get the following error while downloading at least one course:
`TypeError: writelines() argument must be a sequence of strings`

It happens as soon as the .md file is read.
The error references  https://github.com/ankitsejwal/Lyndor/blob/87e3b4bd7ef01811f0439204cbab611ee4c0d0ab/save.py#L176

I thought it might have something to with the course title having a '#' in the title, but the previous  [course](https://www.lynda.com/C-tutorials/C-Essential-Training-1-Syntax-Object-Oriented-Programming/642480-2.html), was able to successfully parse.

Haven't looked into the issue yet

Course(s) affected:
  - https://www.lynda.com/C-tutorials/C-Essential-Training-2-Flow-Control-Arrays-Exception-Handling/642481-2.html

**Comment by ankitsejwal** [comment]
Hi, @thefinalwolf I have made the changes it should be fixed now. As I was not getting this error I was not able to test this solution. Can you please try redownloading the course now and report accordingly?
Thanks in advance.

**Comment by thefinalwolf** [comment]
Got me right before I was headed off to sleep, just tried it.

I now get a Unicode error at the same spot, but I'm able to bypass it by surrounding it with a `try, except ` statement.
Probably better ways like doing a Unicode conversion, but I haven't really read up on that.

**Comment by ankitsejwal** [comment]
Hi @thefinalwolf, python 2.x uses ASCII as a default encoding. This article was of a great help https://gist.github.com/gornostal/1f123aaf838506038710 [Have a look if you are interested to learn few small things](5-10 minutes read).

**Comment by thefinalwolf** [comment]
@ankitsejwal Thanks, I'll read up on it once I'm a little bit more sober :smile:

**Comment by thefinalwolf** [comment]
FYI, the change you did works fine for me btw. I was playing around with the same solution earlier and see I was not removing the `str()` from the result. I tend to shy away from modifying your original code and opt to use `try...except` blocks until I'm more competent with Python; I don't want to break anything.
