### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by tricksterpt** [ankitsejwal/Lyndor#35]
Hello!

Could you guys help me?

![sem titulo](https://user-images.githubusercontent.com/39738738/40669376-b995942a-635e-11e8-8263-ae78a46d6197.jpg)

Thanks!

**Comment by tricksterpt** [comment]
Update:

Type account password and press [Return]:
[lynda:course] Downloading signin page
[lynda:course] Submitting email
ERROR: Unable to download JSON metadata: HTTP Error 418:  (caused by <HTTPError 418: ''>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have the loggin username and password organizational... on the file

**Comment by ankitsejwal** [comment]
Hi, @tricksterpt just to be clear are you using the organizational login to download?
If yes you have to use the cookies method to download the courses.
Please read the README.md and ask for help if needed. 
In short, you have to login to Lynda website using your organizational login and then download cookies.txt file to download courses.
Please get back to me if you have any problem understanding the instruction on README. Please report back whether you succeed or not. Thanks.
Cheers,
ANk

**Comment by tricksterpt** [comment]
Its sad but i dont understand the cookies method...

Thanks in advance...

Cheers!!!

**Comment by tricksterpt** [comment]
Omg its working... I am crying as fuck... Thanks!

**Comment by ankitsejwal** [comment]
Glad to hear it worked for you. Just a kinda survey question - do you think there is a need to update README.md because it's not clear enough?
Thanks
Cheers, 
Ankit

**Comment by tricksterpt** [comment]
Well if you are someone who doesn't understand anything yes...
I just understood it after i open it in Word. Because makes it clear to read.
And there's one point to improve on read me to teach how to switch the cookies and login in orden to use cookies.

Cheers!

**Comment by ankitsejwal** [comment]
Good thanks.
