### ISSUE TITLE
[Bug] Traceback (most recent call last):

### ISSUE THREAD

**Issue by Bneboy** [ankitsejwal/Lyndor#37]
```
Traceback (most recent call last):
  File "C:\Programs\Lyndor-master\run.py", line 130, in <module>
    main()
  File "C:\Programs\Lyndor-master\run.py", line 35, in main
    schedule_download(url)
  File "C:\Programs\Lyndor-master\run.py", line 46, in schedule_download
    if not read.external_downloader:
AttributeError: 'module' object has no attribute 'external_downloader'
Press any key to continue . . .
```

Encountered on Windows 10.

I got this error when pasting in a course link. However, upon further experimentation I found out if I enter ANYTHING - any letter, etc, etc... it comes up with the same error.
This error looked similar to one pictured on the ``report-an-issue.md`` file, but it's slightly different. 
That is all the info I can give to you right now, I will edit this post and give more info later if I find any, thanks.

Running with Python 2.7.15.

**Comment by ankitsejwal** [comment]
HI @Bneboy, are you still facing this problem? Can you send me how you settings.json looks like?
Thanks
ANk
