### ISSUE TITLE
Could not send HEAD request. 503 and 401 error.

### ISSUE THREAD

**Issue by element73** [ankitsejwal/Lyndor#38]
[07/16/18 04:39:03] WARNING: Could not send HEAD request to url.m3u8: HTTP Error 503: Service Unavailable
[07/16/18 04:39:03] ERROR: unable to download video data: HTTP Error 401: Unauthorized

I can send someone my login, so they can test it out. I am trying to download a replay video to view it offline. Is it possible to accomplish this? I tried researching and I am still very new to this. Could inserting cookies or a dev update to youtube-dl solve this problem? I am currently using the youtube-dl gui.

**Comment by ankitsejwal** [comment]
Hi @element73, it seems you are doing it all wrong, but no worries we are here to help you out.
Sure you can download any course for personal offline use but you have to use terminal or command prompt as stated in README.md file on the project page. 
I would need more information to understand exactly what went wrong, consider filling the issue template to let us know about your OS, Python version, course URL, download method etc.
Cheers,
ANk

**Comment by element73** [comment]
Sorry, can you close this thread. I found the solution after searching for hours last night. It wasn't easy... haha

**Comment by ankitsejwal** [comment]
Hi, @element73 can you please let us know what caused the issue and how you fixed it in order to help improve the program. Do you have any suggestions to make?
Thanks.

**Comment by element73** [comment]
As explained by another user on github, the issue is caused by a header-request from the website. Other similar websites have different requirements. Specifically, ESPN+ is looking for an authorization key. I wish i knew how that github user figured that out. You have to find a way to sniff the traffic when you refresh the page with the video (you can use a chrome extension, which is the preferred method). Then search for 'key', and there should only be 2 results showing. In my case, the first result always shows you the key. I copy that key(which is like thousands of characters long). Then use that to insert into the command, --add-header authorization:key, where key is the really long string I copied earlier. And that's it! I used internet download manager to get the link to the highest quality stream (other people have their own method for that). 

Also, I would like to mention that ESPN+ likes to switch up the key sometimes while you're downloading the video. I think they might have a timer on how long the key last, but it seemed random, in my case. 

Please help me on my new issue, I am trying to download videos for a specific course on it's own website (not Udemy).
