### ISSUE TITLE
Library Login 

### ISSUE THREAD

**Issue by mrmark75** [ankitsejwal/Lyndor#39]
Im having trouble using the library_login function. I have added the credentials to the .json file but when I run the Run.Lyndor.bat I always get:
 "[92mUsing username and password combination for download" 
It creates the folder structure and chapters then its prompts:
"Type account password and press [Return]:"  
after I type my library password I get this: 
"[lynda:course] Downloading signin page
[lynda:course] Submitting email
ERROR: Unable to download JSON metadata: HTTP Error 418:  (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

Not sure if I have the .json file setup correctly but no matter what options I try I always get the same result of "Using username and password combination for download". This is my setting config I have removed my org, card, and pin #. 

{
    "credentials": {
        "exfile_download_pref": [ 
            "library-login"
        ], 
        "course_download_pref": [
            "library-login"
        ], 
        "library_login": {
            "organization_url": "XXXXX.XXX", 
            "card_number": "XXXXX", 
            "card_pin": "XXXXX"
        }, 
        "regular_login": {
            "username": "", 
            "password": ""
        }
    }, 
    "preferences": {
        "download_subtitles": true, 
        "download_exercise_file": true, 
        "web_browser_for_exfile": [
            "chrome", 
            "firefox"
        ], 
        "download_time": "", 
        "redownload_course": [
            "prompt", 
            "skip", 
            "force"
        ], 
        "location": "C:\\Users\\Mark\\Videos/Lynda", 
        "ext-downloader-aria2-installed": false,
		"use_cookie_for_download": false
    }
}

**Comment by ankitsejwal** [comment]
Hi @mrmark75 at the moment library credentials are used to download exercise files only.
In order to download entire course you have to use cookie method (organizational login) read: https://github.com/ankitsejwal/Lyndor#if-you-wish-to-download-via-cookies-recommended-for-organizational-login

Your settings.json needs some changes as well then you are good to go. (I've edited your file at two places)
1) "course_download_pref"
2) "exfile_download_pref"
- read comments below

```javascript
{
    "credentials": {
        "regular_login": {
            "username": "",
            "password": ""
        },
        "library_login": {
            "card_number": "XXXXX.XXX",
            "card_pin": "XXXXX",
            "organization_url": "XXXXX"
        },
       // NOTICE: cookies method should be used for organizational login - place "cookies" as first item
        "course_download_pref": [
            "cookies",
            "regular-login"
        ],
        // NOTICE: library credentails can be used to download exercise files - place "library-login" as first item
        "exfile_download_pref": [
            "library-login",
            "regular-login"
        ]
    },
    "preferences": {
        "location": "/Users/ankitsejwal/Movies/Lynda",
        "download_subtitles": true,
        "download_exercise_file": true,
        "web_browser_for_exfile": [
            "firefox",
            "chrome"
        ],
        "ext-downloader-aria2-installed": false,
        "download_time": "",
        "redownload_course": [
            "prompt",
            "skip",
            "force"
        ]
    }
}
```
Hope this helps. I am also working on an update that will have a web interface to help edit settings.json which will be less confusing and much cleaner to use.
Cheers
Ankit

**Comment by mrmark75** [comment]
Ankit,
Thanks for the quick response. I will give your changes a try. I am a little confuse with the cookie.txt file your read.me says to place the file in the downloads or desktop folder? I assume the downloads folder is where the run-lyndor.bat lives? By desktop folder do you mean in the Lyndor-master folder?

**Comment by ankitsejwal** [comment]
@mrmark75 Download and Desktop folder are usual windows or macOS folders. The program can look for multiple cookies.txt files (in Desktop/ Downloads folders) and then pick the latest file and use it for download.
So just install a cookies.txt plugin -> login to Lynda -> download cookies to one of these folders -> tell settings.json to download with the cookies.txt method and you should be good to go.
Cheers.
