### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by putuoka** [ankitsejwal/Lyndor#4]
This is working good but without subtitle. Please include subtitle *.srt file as well on download process. Thank you

**Comment by ankitsejwal** [comment]
Hi @putuoka, I've made the necessary changes to the program, now it downloads the subtitles and then renames the *.srt files to match them with the corresponding videos. 
If you like this repo, a star will be greatly appreciated 👍. I'll be adding few more features in coming days stay connected. 
Thanks !!!
