### ISSUE TITLE
Downloading will pause on a specific command line.

### ISSUE THREAD

**Issue by jawidjrs** [ankitsejwal/Lyndor#47]
## Please follow the guide below

- You will be asked some question, please read them **carefully**
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ankitsejwal/Lyndor/blob/master/README.md)

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with Lyndor) :beetle: 
- [ ] Feature request (request for a new functionality) :point_up:
- [ ] Question :question:
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*,  or you are not completely sure then provide the full terminal output as follows:
Copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
             .
           .d$ .
           d$$  :
          .$$$
          :$$$   :         Download multiple courses
          $$$$   :       at a time, just paste all the
          $$$$   :         urls in Bulk Download.txt
         .$$$$
         :$$$$    :
         $$$$$    :
         :    $$$$$           You can change your
         :    $$$$$       preferences in settings.json
        .:    $$$$$.
       / :    $$$$: \
      /  :    $$$$:  \
     '        $$$$`   '
     |   /:   $$$$\   |
     |  /     $$$` \  |
     |_/   :__$$P   \_|    🏄

1. Paste course url or
2. Press enter for Bulk Download
https://www.lynda.com/Programming-Foundations-tutorials/Foundations-Programming-Databases/412845-2.html

[92mUsing username and password combination for download

Course Name     Programming Foundations: Databases
Course id       412845
Author Name     Simon Allardice
Topics          #Developer      #Programming Foundations        #Databases
Softwares       None
Duration        3h 11m
Release Date    9/30/2015
Downloaded On   22/August/2018
Course URL      https://www.lynda.com/Programming-Foundations-tutorials/Foundations-Programming-Databases/412845-2.html

🌟  info.txt created

Creating Chapters:

00. Introduction
01. Understanding Databases
02. Database Fundamentals
03. Database Modeling  Tables
04. Database Modeling  Relationships
05. Database Modeling  Optimization
06. Database Modeling  Querying
07. Database Modeling  Indexing and Optimization
08. Database Options
09. Conclusion

✅  10 chapters created!!

👍🏻  CONTENT.md created.

[lynda:course] Downloading signin page
[lynda:course] Submitting email
[lynda:course] Submitting password
[lynda:course] 412845: Downloading course JSON
[download] Downloading playlist: Programming Foundations: Databases
[lynda:course] playlist Programming Foundations: Databases: Collected 40 video ids (downloading 40 of them)
[download] Downloading video 1 of 40
[lynda] Downloading signin page
[lynda] 438411: Downloading video JSON
[lynda] 438411: Checking 0-360 video format URL
[lynda] 438411: Checking 0-540 video format URL
[lynda] 438411: Checking 0-720 video format URL
[lynda] 438411: Checking 1-360 video format URL

```
---

### The issue was encountered on:       :computer:
- [ ] MacOS
- [x] Windows
- [ ] Linux

### Enter the python version you are using for download. Find your python version by typing in terminal `python -V`
- python (3.7.0)

---

### If the purpose of this *issue* is a *bug report* please provide all kinds of example URLs where you encountered issues (replace following example URLs by **yours**):
- https://www.lynda.com/Programming-Foundations-tutorials/Foundations-Programming-Databases/412845-2.html
- https://www.lynda.com/Office-tutorials/Office-2016-Office-365-New-Features/378455-2.html

---

### Description of your *issue*, suggested a solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the description is worded well enough to be understood. Provide as much context and examples as possible.

The command line stops at a certain line during downloading which is at this point "[lynda] 513047: Checking 1-360 video format URL" and it doesn't matter which course I download. It always stops there.

**Comment by ankitsejwal** [comment]
Hi @jawidjrs can you try updating your youtube-dl package
```bash
# look at installed packages
$  pip list

# uninstall
$  pip uninstall youtube-dl

# It will install the latest available version
$  pip install youtube-dl
```

Once the downloading is handed to youtube-dl all bugs should be related to youtube-dl, it happens to me sometimes but its rare. Sorry but can't help you alot with this as it's a third party package.

Cheers
ANk

**Comment by ankitsejwal** [comment]
@jawidjrs sorry can't help you enough this time, consider lodging this issue at youtube-dl? https://github.com/rg3/youtube-dl/issues
