### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by jawidjrs** [ankitsejwal/Lyndor#50]
## Please follow the guide below

- You will be asked some question, please read them **carefully**
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ankitsejwal/Lyndor/blob/master/README.md)

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with Lyndor) :beetle: 
- [ ] Feature request (request for a new functionality) :point_up:
- [ ] Question :question:
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*,  or you are not completely sure then provide the full terminal output as follows:
Copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Jawid Payanda>cd C:\Users\Jawid Payanda\Videos\Lynda

C:\Users\Jawid Payanda\Videos\Lynda>Run-Lyndor.bat
             .
           .d$ .
           d$$  :
          .$$$
          :$$$   :            Download multiple courses
          $$$$   :          at a time, just paste all the
          $$$$   :            urls in Bulk Download.txt
         .$$$$
         :$$$$    :
         $$$$$    :
         :    $$$$$      Change preferences in settings.json
         :    $$$$$        Run python settings/settings.py
        .:    $$$$$.
       / :    $$$$: \
      /  :    $$$$:  \
     '        $$$$`   '
     |   /:   $$$$\   |
     |  /     $$$` \  |
     |_/   :__$$P   \_|    🏄

1. Paste course url or
2. Press enter for Bulk Download
https://www.lynda.com/SQL-tutorials/Learning-SQL-Programming/548044-2.html

[92m⛺  Using username and password combination for download

Course Name     Learning SQL Programming
Course id       548044
Author Name     Scott Simpson
Topics          #Developer      #Databases
Softwares       #SQL    #SQLite
Duration        1h 27m
Release Date    8/15/2017
Downloaded On   24/August/2018
Course URL      https://www.lynda.com/SQL-tutorials/Learning-SQL-Programming/548044-2.html

🌟  info.txt created

Creating Chapters:

00. Introduction
01. Ask for Data from a Database
02. Ask for Data from Two or More Tables
03. Data Types  Math  and Helpful Functions
04. Add or Modify Data
05. Conclusion

✅  6 chapters created!!

👍🏻  CONTENT.md created.

Traceback (most recent call last):
  File "C:\Users\Jawid Payanda\Downloads\Programs\Lyndor-master/run.py", line 133, in <module>
    main()
  File "C:\Users\Jawid Payanda\Downloads\Programs\Lyndor-master/run.py", line 35, in main
    schedule_download(url)
  File "C:\Users\Jawid Payanda\Downloads\Programs\Lyndor-master/run.py", line 51, in schedule_download
    download_course(url)
  File "C:\Users\Jawid Payanda\Downloads\Programs\Lyndor-master/run.py", line 101, in download_course
    save.videos(url, cookie_path, course_folder_path)   # Download videos
  File "C:\Users\Jawid Payanda\Downloads\Programs\Lyndor-master\save.py", line 234, in videos
    cookie = ' --cookies ' + '"' + cookie_path + '"'     # cookie
TypeError: can only concatenate str (not "NoneType") to str
Press any key to continue . . .

```
---

### The issue was encountered on:       :computer:
- [ ] MacOS
- [x] Windows
- [ ] Linux

### Enter the python version you are using for download. Find your python version by typing in terminal `python -V`
- python (3.7.0)

---

### If the purpose of this *issue* is a *bug report* please provide all kinds of example URLs where you encountered issues (replace following example URLs by **yours**):
https://www.lynda.com/MySQL-tutorials/Database-Clinic-MySQL/609013-2.html
https://www.lynda.com/SQLite-tutorials/Database-Clinic-SQLite/588032-2.html
---

### Description of your *issue*, suggested a solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the description is worded well enough to be understood. Provide as much context and examples as possible.
Every time I run run-lyndor.bat on command prompt it encounters with same error.

**Comment by ankitsejwal** [comment]
Hi @jawidjrs sorry for messing things up with the last update, last update was relatively big and had some breaking changes hence you are facing these issues. Please do report if you find any more once you test this patch.
Thanks.
