### ISSUE TITLE
FileNotFoundError: [WinError 3]

### ISSUE THREAD

**Issue by zfv9** [ankitsejwal/Lyndor#52]
Hello,

is this a bug or something else?

> Traceback (most recent call last):
> File "C:\XXXXX\Downloads\Lyndor-master/run.py", line 133, in <module>main()
> File "C:\XXXXX\Downloads\Lyndor-master/run.py", line 32, in main schedule_download(url)
> File "C:\XXXXX\Downloads\Lyndor-master/run.py", line 51, in schedule_download download_course(url)
> File "C:\XXXXX\Downloads\Lyndor-master/run.py", line 99, in download_course save.chapters(url, course_folder_path)              # Create chapter folders
> File "C:\XXXXX\Downloads\Lyndor-master\save.py", line 168, in chapters os.mkdir(course_folder_path + "/" + chapter) # create folders (chapters)
> FileNotFoundError: [WinError 3]

Thanks

**Comment by ankitsejwal** [comment]
Hi @zfv9 what is the course url and are you facing this bug on other courses as well ?

**Comment by zfv9** [comment]
Hi ankitsejwal thank you for your support!

Unfortunately yes in some other courses - here's one example: https://bit.ly/2PcBPwp

**Comment by ankitsejwal** [comment]
I think it this is due to windows not allowing special characters like Blöcke - windows has stricter restriction with such characters and do not allow these names as a directory name. 
You must not be getting these error on chapters with english characters?

**Comment by zfv9** [comment]
I can create manually folder included names with non english characters like öüä..

Or should do it with python?

**Comment by ankitsejwal** [comment]
Can you try creating a new python file -> test.py and then write following code and run it(python test.py):

```python
import os 
os.mkdir('4. Datenextraktionen und Abhängigkeiten')
```
See if it creates a folder. 
Was there more line to this error log?

**Comment by zfv9** [comment]
It works - the folder got created..

**Comment by ankitsejwal** [comment]
Alright was there any more lines to the error, can you send me the full log here? Thanks
