### ISSUE TITLE
install.py error

### ISSUE THREAD

**Issue by sutaj** [ankitsejwal/Lyndor#58]
I have an issue while installing:

```
('lyndor path:', '/home/akil/Lyndor/')
sh: 1: pip: not found

>>> Courses will be saved at -> /home/akil/Videos/Lynda

-> settings.json file created at Lyndor/settings/static/js/settings.json

>>> Lynda folder already exists

-> Bulk Download.txt file created successfully.


-> Downloading web driver for linux
Traceback (most recent call last):
  File "install.py", line 77, in <module>
    save.webdriver()
  File "/home/akil/Lyndor/module/save.py", line 415, in webdriver
    chrome = requests.get(chrome_url)
UnboundLocalError: local variable 'requests' referenced before assignment
```

Readme have lots of information, but this really important, not so much :/

**Comment by ankitsejwal** [comment]
Hi @sutaj it seems pip is not installed in your system. Pip is the package manager for Python and is a must-have if you want to install third-party packages, please try installing pip https://www.makeuseof.com/tag/install-pip-for-python/ and then run install.py again.
Please ask any further questions if you are stuck anytime. I hope this helps.
Cheers
Ankit
