### ISSUE TITLE
Need help in downloading bulk

### ISSUE THREAD

**Issue by itsmemac** [ankitsejwal/Lyndor#61]
using windows version of lyndor
Now am able to download single courses, how do i download in bulk?
have pasted courses link in bulk download.txt as each link in each line.
Is the formatting of the link wrong? help needed

**Comment by ankitsejwal** [comment]
Hi @itsmemac after pasting all the links on a separate line you just have to save bulk download.txt
Then run the program and press enter to download using bulk download method.
Cheers

**Comment by itsmemac** [comment]
![capture](https://user-images.githubusercontent.com/37410297/45530101-97268a00-b806-11e8-9231-ec2af39bc48d.JPG)
This is how the links are pasted in the bulk download.txt
but when i click enter in the program and it just downloads the first course and gives me "program has ended. press any key to continue"
it doesn't download the next links

**Comment by ankitsejwal** [comment]
@itsmemac that's weird its working over here can you delete your Bulk Download.txt and replace it with this one and try again? 
[Bulk Download.txt](https://github.com/ankitsejwal/Lyndor/files/2382068/Bulk.Download.txt)

**Comment by itsmemac** [comment]
![capture1](https://user-images.githubusercontent.com/37410297/45533458-55511000-b815-11e8-8b60-c3844e7ff2b7.JPG)

**Comment by itsmemac** [comment]
tried by removing "." from the file name and still it downloaded only the first course and didnt go for the second one

**Comment by ankitsejwal** [comment]
Were you able to replace the file as in the Lynda folder? It should not give file not found error
<img width="511" alt="screen shot 2018-09-14 at 5 43 52 pm" src="https://user-images.githubusercontent.com/13817482/45536840-f5269200-b845-11e8-927c-a5ea373c0559.png">

**Comment by itsmemac** [comment]
> Were you able to replace the file in the Lynda folder? It should not give file not found error
> <img alt="screen shot 2018-09-14 at 5 43 52 pm" width="511" src="https://user-images.githubusercontent.com/13817482/45536840-f5269200-b845-11e8-927c-a5ea373c0559.png">

yup, still the same issue.
it just downloads the first course and then nothing
had to remove "." from the file name of bulk download.txt to make lyndor recognize

**Comment by ankitsejwal** [comment]
Can't reproduce this issue on my mac, @Otech-Man can you please try to reproduce this issue?
Thx

**Comment by Otech-Man** [comment]
@ankitsejwal yeah sure man, let me download you last version and then I'll use your text file

**Comment by Otech-Man** [comment]
@itsmemac @ankitsejwal just tried and downloads launch as usual, nothing on my end

**Comment by ankitsejwal** [comment]
Thanks for testing @Otech-Man, @itsmemac sorry but for now you have to fight this battle alone mate.

**Comment by itsmemac** [comment]
Thank you for trying to fix the issue @Otech-Man @ankitsejwal 
Will try again. Is it something to do with chromedriver as it gives me error of attachment download
and when i click continue, it just goes to end.

**Comment by itsmemac** [comment]
Fixed it. It was the chromedriver issue.
Re-downloaded chromedriver and added the path to system environment and did a restart
and boom it works. thanks for this awesome application.
Saves me a ton of time.

**Comment by katzka** [comment]
since lynda became linkedin learning, there is no valid url for the courses. My course url looks like this
https://www.linkedin.com/learning/javascript-essential-training-3/add-javascript-in-an-external-file?collection=urn%3Ali%3AlearningCollection%3A6581545581339119616
when i run Run-Lyndor.bat it starts than it is asking for a valid url
Can you help us with this? Thanks a lot

**Comment by ankitsejwal** [comment]
@katzka have you tried this url: https://www.lynda.com/JavaScript-tutorials/JavaScript-Essential-Training/574716-2.html for the same course?

**Comment by katzka** [comment]
my premium account is opened in linkedin learning, when i paste the url u gave me it redirects me to Lynda and it is asking for user and password but the one i have, is from linkedin learning and is not valid in lynda. Looks like after lynda became linked in learning there are 2 separate accounts. the Lynda is closed for new members. Your code works for Lynda not for Linked in learning
 But thanks anyway
