### ISSUE TITLE
Breaks when making folder with copyright sign

### ISSUE THREAD

**Issue by vi2606** [ankitsejwal/Lyndor#63]
Hello!
Using Lyndor on Ubuntu 1604.
I noticed the downloader breaks when course name has copyright sign in it while trying to make folder.
Errors are bellow ...

I fixed errors for now by adding copyright sign to `replacements `array in save.py, move.py.

Please check ! :)

Have a nice day!

1st error:
Traceback (most recent call last):
  File "run.py", line 137, in <module>
    main()
  File "run.py", line 36, in main
    schedule_download(url)
  File "run.py", line 55, in schedule_download
    download_course(url)
  File "run.py", line 100, in download_course
    save.course(url, lynda_folder_path)                 # Create course folder
  File "/home/vi420/Downloads/Lyndor/module/save.py", line 98, in course
    print('\ncreating course folder at: {}'.format(current_course))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 74: ordinal not in range(128)

2nd error:
Traceback (most recent call last):
  File "run.py", line 137, in <module>
    main()
  File "run.py", line 36, in main
    schedule_download(url)
  File "run.py", line 55, in schedule_download
    download_course(url)
  File "run.py", line 107, in download_course
    move.vid_srt_to_chapter(url, course_folder_path)    # Move videos and subtitles to chapter folders
  File "/home/vi420/Downloads/Lyndor/module/move.py", line 71, in vid_srt_to_chapter
    print('🔰  Moving files inside: ' + str(chapter_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 22: ordinal not in range(128)

**Comment by ankitsejwal** [comment]
Hi @vi2606 thanks for reporting this, can you let us know the course URL and Python version.

**Comment by vi2606** [comment]
Courses were:
https://www.lynda.com/Project-Management-tutorials/Exam-Tips-Project-Management-Professional-PMP/679615-2.html
https://www.lynda.com/Project-Management-tutorials/Cert-Prep-Project-Management-Professional-PMP/659716-2.html

`python -V
Python 2.7.12
`

**Comment by ankitsejwal** [comment]
Python 2 is a pain when it comes to Unicode. I dropped support for Python version < 3.6 in order to maintain lesser bugs related to Unicode errors and utilize some latest feature in Python 3.6 #64
