### ISSUE TITLE
Issue with installing

### ISSUE THREAD

**Issue by itsmemac** [ankitsejwal/Lyndor#65]
Due to mistake i deleted perfectly working lyndor, 
when i tried to install lyndor from fresh download of master using install.bat, it shows me these errors

CMD without administrator
![1](https://user-images.githubusercontent.com/37410297/45837282-9f158b00-bd2c-11e8-8b0d-81f428087b2c.JPG)

CMD with administrator
![2](https://user-images.githubusercontent.com/37410297/45837297-a3da3f00-bd2c-11e8-82ea-e4084d471f90.JPG)

Help me fix this issue.
All the requirement are installed.
Python is in path
Environmental Variable added
Python version : 3.7.0
OS : Windows 10 Home x64

**Comment by ankitsejwal** [comment]
It may be due to install.bat still launching Python2.7, can you replace C:\Python27 in line 3 with the path of your Python3 folder (I don't know the path but it should be similar) and also change the line 4 to:
python3 "install.py"

install.bat:
```bat
1) @ECHO OFF

2) REM Batch file to execute install.py

3) SET PATH=%PATH%;C:\Python27;C:\Python27\Scripts

4) python "install.py"

5) pause
```
Otherwise just open terminal to type
```bash
$ python3 whatever/path/to/install.py
# this should run install.py with python3 interpreter
```

**Comment by itsmemac** [comment]
Tried the above step already
it didnt work.

Fixed it by uninstalling all python
Setting directory in cmd and selecting install.bat in cmd and executing it.
Worked
