### ISSUE TITLE
Exercise files not downloading

### ISSUE THREAD

**Issue by kanevsr** [ankitsejwal/Lyndor#70]
When I do a bulk download using Organization login (cookies.txt) on Windows and set to download the exercise files I get an error when the script tries to download them and does not do it.

[0928/084957.224:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:12104/devtools/browser/50374aed-3759-490d-932e-4a3626de4f2c

P.S. I am using Chrome for download and aria2 also which is set up properly

**Comment by ankitsejwal** [comment]
Hi @kanevsr exercise files cannot be downloaded using organization login https://github.com/ankitsejwal/Lyndor#exercise-files-download

**Comment by simioluwatomi** [comment]
I am having this same issue but I have library login details set up in my settings.json file and followed the instructions [here](https://github.com/ankitsejwal/Lyndor#exercise-files-download). I use Win 10 and wouldn't mind posting screenshots of my system Path. What could be the problem?

![untitled](https://user-images.githubusercontent.com/22191563/46997141-d5211180-d116-11e8-9540-714daef7a3eb.png)
![untitled2](https://user-images.githubusercontent.com/22191563/46997143-d5b9a800-d116-11e8-8fef-56271586ea0d.png)

**Comment by ankitsejwal** [comment]
Hi @simioluwatomi what happens after username and password is entered, do you get to the course page in a web browser automatically?

**Comment by simioluwatomi** [comment]
It does not launch any page in my browser... I think the project's ```readme``` needs a little finetuning. According to the docs, 

> unzip both the ***driver.zip files to reveal the actual files inside it, then copy the webdriver folder path to add to your PATH variable.

But should the zip files be extracted into their own dedicated folders or into the contents of the zip files should be extracted into the webdriver folder? I'll continue playing around with different combinations and see which one works
