### ISSUE TITLE
URL input not possible

### ISSUE THREAD

**Issue by tersenius** [ankitsejwal/Lyndor#8]
Hi,

I'm trying to run Lyndor in a fresh python3 installation on MacOS. When I run run.py, I get to the point where the rocket is displayed, the activity indicator rotates a bit and then:

> 1. Paste course url or
> 2. Press enter for Bulk Download

is displayed.

However, there is no chance to go for either 1. or 2., as instantly I get:
> Traceback (most recent call last):
  File "/Lyndor-master/run.py", line 109, in <module>
    main()
  File "/Lyndor-master/run.py", line 21, in main
    url = raw_input()
NameError: name 'raw_input' is not defined

Also, specifying the URL in Bulk Download.txt did not help.

Yours,
Ronald

**Comment by ankitsejwal** [comment]
Hi Ronald,

Can you try replacing raw_input() to input() in run.py - I search online they say, its been renamed to input() in python 3, although it works for me one my system.
Please give it a try.

Cheers,
-Ankit

**Comment by ankitsejwal** [comment]
Hi @tersenius I've pushed a new update, it fixes the issue on python3 now, remember to edit settings.json according to your need, set your preferences how would you like to download the course i.e. via cookies or username and password combination.
Please feel free to post issues here, happy to help.

Cheers,
Ank

**Comment by tersenius** [comment]
Hi Ank,

thanks for your support, in an incredible speed!

Re-downloaded the files, changed settings and the URL input problem is solved now! When I enter a URL, the script continues. It sets up the appropriate structure in the Movies folder.

Next there is an issue with cookies, the method of authorization I'm using:
> Traceback (most recent call last):
  File "/Lyndor-master/run.py", line 115, in <module>
    main()
  File "/Lyndor-master/run.py", line 37, in main
    schedule_download(url)
  File "/Lyndor-master/run.py", line 51, in schedule_download
    download_course(url)
  File "/Lyndor-master/run.py", line 96, in download_course
    download.download_files(url, cookie_path, course_folder_path) # Downloading lynda videos to course folder
  File "/Lyndor-master/download.py", line 30, in download_files
    cookies.edit_cookie(cookie_path, message.NETSCAPE) # Edit cookie file
  File "/Lyndor-master/cookies.py", line 26, in edit_cookie
    add_new_line(cookie, line)
  File "/Lyndor-master/cookies.py", line 11, in add_new_line
    with file(cookie, 'r') as original: data = original.read()
NameError: name 'file' is not defined

cookies.txt is current and located in Downloads folder.

Cheers,
Ronald

**Comment by ankitsejwal** [comment]
Hi @tersenius ,
Sorry, you're facing all this problem as I didn't test the program on python3 earlier.
I've fixed this new issue with this recent commit.
[In this recent case, python changed the {with file} function from python2 -to- {with open} keyword in python3].

Cheers,
Ank

**Comment by tersenius** [comment]
Hi Ank,

no worries, I'm happy to test python3 for you. And now it does work indeed, I was able to download the first course. So thanks for all your efforts!

There seems to be an issue with non-ASCII characters though. I can download English courses without any problems. If I try this with German ones (who happen to have umlauts like äöü in the titles), the download fails:
> [generic] 500205-2: Requesting header
WARNING: Could not send HEAD request to https://www.lynda.com/de/Photoshop-tutorials/Fullmethoden-naturliche-Portrats/500205-2.html: HTTP Error 401: Unauthorized
[generic] 500205-2: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 500205-2: Extracting information
ERROR: Unsupported URL: https://www.lynda.com/de/Photoshop-tutorials/Fullmethoden-naturliche-Portrats/500205-2.html

For example, the folder for the course "Photoshop: Füllmethoden für natürliche Porträts" is named "Photoshop - F -llmethoden f -r nat -rliche Portr -ts" on disk, suggesting ä and ü being transformed to " -".
In the chapters folders however, "Einführung" is converted to "Einf hrung", the special character simply being ommitted.

Could this be causing the header request to fail?

**Comment by ankitsejwal** [comment]
Hi @tersenius,

I'm glad it worked, I'll have a look at the new issue with German courses in a couple of days.
Thanks for reporting all these bugs, it really helps to improve.

Cheers,
ANk

**Comment by tersenius** [comment]
I've had a second look into this, using youtube-dl directly for this download. Here I get the same error. So this seems to be related to youtube-dl, not your script.

Thanks again for your support!

Cheers,
Ronald

**Comment by ankitsejwal** [comment]
Hi @tersenius, Thanks for creating an issue at the youtube-dl repo, according to them looks like they've relaxed URL restrictions with the new software, but apparently I am not able to download the latest version: https://github.com/rg3/youtube-dl/releases/tag/2018.01.07 through pip.
Were you able to download this version and test it?

Cheers,
Ankit

**Comment by tersenius** [comment]
I've just downloaded the lynda.py extractor script manually and this did work.

Cheers,
Ronald

**Comment by ankitsejwal** [comment]
Great, I've updated the code to accommodate German and other languages, now the chapter name should be saved as expected. Also, now you can download Exercise files (but it will not work for organizational login).

Cheers,
Ankit
