### ISSUE TITLE
Download stops with youtube-dl error

### ISSUE THREAD

**Issue by mmBesar** [ankitsejwal/Lyndor#87]
## Please follow the guide below

- You will be asked some question, please read them **carefully**
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/ankitsejwal/Lyndor/blob/master/README.md)

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with Lyndor) :beetle: 
- [ ] Feature request (request for a new functionality) :point_up:
- [ ] Question :question:
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*,  or you are not completely sure then provide the full terminal output as follows:
Copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
ERROR: None: Failed to parse JSON  (caused by JSONDecodeError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### The issue was encountered on:       :computer:
- [ ] MacOS
- [x] Windows
- [ ] Linux

### Login method:
- [ ] Regular login (username + password)
- [ ] Organization login (cookies.txt)
- [x] cookies.txt + Library login(for exercise file)

### Enter the python version you are using for download. Find your python version by typing in terminal `python -V`
- python (Python 3.7.3) [replace (version) with your python version like: python 3.6.3]

---

### If the purpose of this *issue* is a *bug report* please provide all kinds of example URLs where you encountered issues (replace following example URLs by **yours**):
- https://www.lynda.com/Illustrator-tutorials/Logo-Design-Techniques-Revision/2800333-2.html

---

### Description of your *issue*, suggested a solution and other information

The download of the above URL stops at the 22 video of 57 with the error above!

**Comment by Harshitbasti** [comment]
```
[download] Downloading video 7 of 18
[youtube] Ab_j-TenDRs: Downloading webpage
[download] Resuming download at byte 10743808
[download] Destination: FRM Level 1 _ Basic Statistics _ Part 4-Ab_j-TenDRs.f248.webm
[download] 100% of 618.21MiB in 43:43
[download] Destination: FRM Level 1 _ Basic Statistics _ Part 4-Ab_j-TenDRs.f251.webm
[download] 100% of 70.37MiB in 07:47
[ffmpeg] Merging formats into "FRM Level 1 _ Basic Statistics _ Part 4-Ab_j-TenDRs.webm"
Deleting original file FRM Level 1 _ Basic Statistics _ Part 4-Ab_j-TenDRs.f248.webm (pass -k to keep)
Deleting original file FRM Level 1 _ Basic Statistics _ Part 4-Ab_j-TenDRs.f251.webm (pass -k to keep)
```


I don't know why youtube-dl is downloading same video 2 times. First time it is downloading video with original file size and then downloading it with smaller size.

Also videos are blurr

Please help me out with this issue.

**Comment by jawidjrs** [comment]
I got the same error with this course"Become a CompTIA A+ (220-1001 and 220-1002) Certified Technician". but two other courses were download normaly. I mean these "Overcoming Cognitive Bias" and "Overcoming Cognitive Bias"
ERROR was :ERROR: None: Failed to parse JSON  (caused by JSONDecodeError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
