### ISSUE TITLE
How to download Exercise Files ?

### ISSUE THREAD

**Issue by kurniaoone** [ankitsejwal/Lyndor#9]
can you help me ? i want download Exercise Files too with this script :)

**Comment by ankitsejwal** [comment]
Hi @kurniaoone, sadly this feature is yet to be implemented, right now you cannot download exercise files with this program, I am working on the solution. Please be ensured I'll let you know once this feature is added. I hope the rest of the user experience is good enough(installing and using the program)?

Cheers,
Ank

**Comment by ankitsejwal** [comment]
Hi @kurniaoone, this feature is implemented now. organizational login being an exception.
You will need to run install.py again to install the latest program after downloading the latest release to accommodate the changes. Also, read the README.md to set up the exercise file part.

Cheers,
Ank

**Comment by kurniaoone** [comment]
Hi @ankitsejwal thanks, you're awesome :+1:

**Comment by ankitsejwal** [comment]
Thanks @kurniaoone
