### ISSUE TITLE
WARNING: Do not use the development server in a production environment

### ISSUE THREAD

**Issue by sankalpgaikwad** [ankitsejwal/Lyndor#93]
Serving Flask app "website1" (lazy loading)
* Environment: production
  WARNING: Do not use the development server in a production environment.
  Use a production WSGI server instead.
* Debug mode: on
* Restarting with stat
* Debugger is active!
* Debugger PIN: 672-977-358
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

**Comment by buiminh15** [comment]
I had same issue and I could not access the link http://127.0.0.1:5000/
What should I do now???

**Comment by ankitsejwal** [comment]
Hi @buiminh15 @sankalpgaikwad please 
- update your settings folder to the latest release, then 
- pip install -r requirements.txt (This will install a new module and update existing modules)
- Then finally type - flask run (You should be inside Lyndor folder)

```bash
$ pip install -r requirements.txt
$ flask run
```

Hope it resolves the issue.
Cheers
