### ISSUE TITLE
sh: youtube-dl: command not found

### ISSUE THREAD

**Issue by exiled96** [ankitsejwal/Lyndor#99]
I got This error any 
youtube-dl is installed and working but when i run the script i get that error 
help 

 11 chapters created!!

  CONTENT.md created.

sh: youtube-dl: command not found

  Renaming video/subtitle files

Videos available: 49
Videos downloaded: 0

 Moving files inside: 00. Introduction
File not found: 01 - Cloud concepts.mp4
  File not found: 02 - What you need to know.mp4
  File not found: 03 - The goals of information securi

**Comment by ankitsejwal** [comment]
if you run this command in your terminal 
```bash
youtube-dl
```
Are you getting an error?
